import Head from "next/head";
import Image from "next/image";
import Button from "../Atoms/Button";
import Card from "../Atoms/Card";
import { HeadingL, Paragraph, SubHeading } from "../Atoms/Typography";
import PricingCard from "../Molecules/PricingCard";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* planTitle, price, billedPer, features */}
        <PricingCard
          planTitle="Basic"
          price="FREE"
          billedPer="Up to 5 users for free"
          features={[
            "Basic Document Collaboration",
            "2 GB Storage",
            "Great Security Support",
          ]}
        />
        {/* <Button>I am a normal default type of button</Button>
        <Button size="small">I am a smaller button!</Button>
        <Button size="large">I am a smaller button!</Button>
        <Button variant="secondary">I am a secondary button</Button>
        <HeadingL> Hello World</HeadingL>
        <HeadingL textColor="black-light"> Hello World</HeadingL>
        <Paragraph textColor="black-light">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, omnis
          maxime, magnam non animi sunt expedita officiis illo, facere quos
          laudantium nobis distinctio perferendis iusto id ab consequuntur.
          Labore, repudiandae?
        </Paragraph>
        <Card
          className="p-l"
          shadow={true}
          variant="primary"
          style={{ padding: "60px" }}
        >
          <SubHeading>Hello!</SubHeading>
          <SubHeading textColor="black-light">Hello!</SubHeading>
        </Card> */}
      </main>
    </div>
  );
}
